# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 573c7f83705839b00e21ab0baeb6d9c8d60164eb306399c7b64ecf053ecba3d1d42d6a747af6ba20319c26e7fb244c64a8a432422885ee6616c20f7a6431815f

test:
  secret_key_base: e934f59ddfca1e3e866171c9fb2e2ccf873b2c7c6090d48c4fd97f06b0746cdfa05ce95efd0ddd12afb93833e8e322603456c9e5c4146c644df087843702b6eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
